### ISSUE TITLE
Open .EIT files

### ISSUE THREAD

**Issue by jannisborn** [liubenyuan/pyEIT#10]
Sorry for the potentially dumb question:

I'm new to EIT but got access to lung EIT data from COVID patients, saved in `.eit` format. I would like to visualize the data and visually inspect it. I installed the package, but I'm lost on how to start. Do you have any standalone documenation website (e.g. made with Sphinx and hosted with github pages)?
Basically, I'm just searching for a way to open `.eit` files on Mac OS.

Thanks a lot!

**Comment by liubenyuan** [comment]
what's the file format definitions of the `.eit` file?

There is a simple document on how pyeit parses the data, 
https://github.com/liubenyuan/pyEIT/blob/master/doc/pyEIT-data_format.pdf

You should write a wrapper in `pyeit/io` to parse the `.eit` data in any of the format that pyeit supports.

**Comment by liubenyuan** [comment]
> Sorry for the potentially dumb question:
> 
> I'm new to EIT but got access to lung EIT data from COVID patients, saved in `.eit` format. I would like to visualize the data and visually inspect it. I installed the package, but I'm lost on how to start. Do you have any standalone documenation website (e.g. made with Sphinx and hosted with github pages)?
> Basically, I'm just searching for a way to open `.eit` files on Mac OS.
> 
> Thanks a lot!

I can help you with the file format conversion if the data format of `.eit` is available.

**Comment by jannisborn** [comment]
Thanks for the pointers @liubenyuan! Unfortunately, I don't think I'm capable of writing a converter since I never worked with EIT data before.

The software I was given for processing the files is from here: https://draeger-msi.de/en/services_en/downloads/.

It would be great if you're willing to help, I can send you an example file I have. Or would the recommended guideline to use a Windows machine with the mentioned software for analysis?

**Comment by liubenyuan** [comment]
The wrapper would be best written with a detailed manual on the `.eit` binary file format.

I can write a `.eit` parser for you, using the information already exists in the EIDORS package: http://eidors3d.sourceforge.net/doc/index.html?eidors/interface/eidors_readdata.html
Though, I need a sample `.eit` data, as well as the images at two different time stamps, for example, an EIT image at frame 100 with the reference frame data set to the 0th frame, so that I could check whether the file parser I wrote is correct.

**Comment by jannisborn** [comment]
Thanks a lot @liubenyuan, that would be great.
I should be able to share an example file with you. I'll contact you directly.

**Comment by kelades** [comment]
Hi, 
I have the exact same problem with @jannisborn. Would it be possible to share some information about the parser? 
Thanks for any help!

**Comment by liubenyuan** [comment]
@kelades I haven't EIT file format definition (nor an .EIT file) at hand. I would like to help extending pyeit with .EIT extension if this information are available.

**Comment by liubenyuan** [comment]
@jannisborn @kelades 
Here are two MATLAB scripts in parsing .eit file format
https://github.com/ybk2810/EIT_ImageProcessing/blob/master/EIT/ST_EIT_reader.m
https://github.com/EIT-team/Load_data/blob/master/src/matlab/SwissTom_EIT_reader.m

And here is a sample `.eit` file,
https://github.com/EIT-team/Load_data/blob/master/resources/data/SwissTom/r-phantom.eit

Is this the eit file format you are using?

**Comment by kelades** [comment]
Thank you for your reply. Yes this is the format I have my data in. Currently, I am trying to run the matlab scripts  (the ones you already mentioned) to parse them  - but I am still looking for a solution in Python.  
As I understood from what's been said, there isn't a parser to read data from a `.eit` file format and I would need to write it on my own , right?  If I can find some time, I would like to give it a try - do you  have some guidelines you can share, as I am not familiar with this kind of data and I don't know where to start ?

**Comment by liubenyuan** [comment]
Are your data swisstom AG format or Daeger (pulmovista) format? Yes, you need a parser in pyeit, I can write for you given there is a sample data (i.e., a .eit file collected using your device). I can port the code in EIDORS in pyeit. A sample reconstructed image, is also helpful.

**Comment by kelades** [comment]
That would be extremely helpful. Unfortunately I don't have a reconstructed image for validation ( that 's one of my goals. parse the data and then produce the reconstructed images).
Would you like me to upload a sample file here?

**Comment by liubenyuan** [comment]
Sure, I can use the sample file for validation.

**Comment by kelades** [comment]
This is the data file (github doesn't support `.eit` so I put them in a zip)
[data.zip](https://github.com/liubenyuan/pyEIT/files/5383653/data.zip)

**Comment by liubenyuan** [comment]
![a](https://user-images.githubusercontent.com/171338/96202978-49574f80-0f93-11eb-97d0-b862e9785d26.png)
![b](https://user-images.githubusercontent.com/171338/96202981-4bb9a980-0f93-11eb-8b50-8a57a7c63b4e.png)

@kelades 

Is this the result you expected. Note that the mesh does not match a throax shape, and the orientation and locations of electrodes may not be the way you are using. You should use your own mesh, and electrodes locations.

If it is ok, I will clean up the codes and create a PR so you can use it. BTW, is it ok that I upload a slice of this data (60 frames) on `pyeit/app` and refer to this issue?

**Comment by kelades** [comment]
yes I think that would be it.  Ok, noted for the meshes. Yes , ok abou the slice of data. Thank you very much for your help, much appreciated

**Comment by liubenyuan** [comment]
@kelades I update pyeit and the reproducible code using a slice of your data are put into
https://github.com/liubenyuan/pyeit-apps/tree/master/daeger
I am glad to help if you encounter any problem in using pyeit.

*Thank you for your data and you are welcome to pull some PRs for* [pyeit](https://github.com/liubenyuan/pyEIT) or [pyeit-apps](https://github.com/liubenyuan/pyeit-apps)
