### ISSUE TITLE
export 3d image

### ISSUE THREAD

**Issue by lanzithinking** [liubenyuan/pyEIT#11]
hi benyuan, nice work! Do you have any plan to add functionality to export 3d image to png file? Your 'tetplot' function plots figures in interactive mode. But it would be nice to save them. Thanks!

**Comment by liubenyuan** [comment]
This function use vispy for 3D rendering, it currently (AFAK) do not have production ready image export function.

You may try mayavi for 3D plot. Thanks for your support :)

**Comment by lanzithinking** [comment]
Thanks for the reply. I will have a try.
