### ISSUE TITLE
negative permittivity

### ISSUE THREAD

**Issue by lanzithinking** [liubenyuan/pyEIT#12]
hi benyuan, I want to ask a naive question. In your model, you do not restrict permittivity \sigma to be positive. This makes the model extremely sensitive to sigma (esp. in negative domain) and resulting log-likelihood (objective function) very rough. According to your paper in 2018, it is for analysis of multi-frequency EIT (possibly complex solutions)? Is there any realistic consideration for not requiring positive permittivity? What is it? Thanks!

**Comment by liubenyuan** [comment]
In reality, perm is complex valued and the conductivities are positive. In forward simulation, it's ok. In inverse imaging, you can constraint conductivities being postive, which may provide better reconstruction results in static imaging.

Most of the real life application is using time difference, or frequency difference imaging. So this constraint may not be mandatory.

**Comment by fbbarnes** [comment]
Hello, please could you let me know how to constrain the conductivities to being positive? Many thanks.

**Comment by liubenyuan** [comment]
Hi, in dynamic EIT imaging the changes in conductivities can be negative. In static imaging, you should impose nonnegative constraints on sigmas as a prior, using algorithm such as nonnegative least square. I am not a pro on this, you may give osqp a try.

**Comment by fbbarnes** [comment]
Hi, where can the nonnegative constraints be applied in pyEIT? I'm trying to do get a conductivity map with static measurements. Thank you.

**Comment by liubenyuan** [comment]
You should rewrite and derive your own algorithm using non-negative constraints. The static imaging code is `gs` in `jac.py`.
