### ISSUE TITLE
Protocol and boundary condition implementation

### ISSUE THREAD

**Issue by SetsunaRiku** [liubenyuan/pyEIT#16]
You can open a new issue on this.

You should pass `parser=fmmu` if you are using `rotate-meas` protocol. i.e., If your electrodes are numbered as [1..8], if now (the stimulation pattern) the the source and sink of current are 4-5, then the 5 voltgaes differences are V67, V78, V81, V12, V23.

The following are the codes, you may try using interpolation for a smoothed display

```python
# coding: utf-8
""" demo on static solving using JAC (experimental) """
# Copyright (c) Benyuan Liu. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.
from __future__ import division, absolute_import, print_function

import numpy as np
import matplotlib.pyplot as plt

# pyEIT 2D algorithms modules
from pyeit.mesh import create
from pyeit.eit.utils import eit_scan_lines
import pyeit.eit.jac as jac

""" 1. setup """
n_el = 8
mesh_obj, el_pos = create(n_el, h0=0.12)
el_dist, step = 1, 1
ex_mat = eit_scan_lines(n_el, el_dist)
pts = mesh_obj["node"]
tri = mesh_obj["element"]

fv = np.array([0.1887, 0.0921, 0.0565, 0.065, 0.1809,
               0.1602, 0.0666, 0.0598,0.1022, 0.1538,
               0.1526, 0.0867, 0.0996, 0.0932, 0.1436,
               0.1547,0.106, 0.0703, 0.0672, 0.1442,
               0.1742, 0.076, 0.0527, 0.0763,0.1893,
               0.1381, 0.0621, 0.0667, 0.1047, 0.1907,
               0.1745, 0.1185,0.1263, 0.1361, 0.183,
               0.1906, 0.124, 0.0955, 0.0823, 0.1522]) # in volt

""" 3. solve_eit using gaussian-newton (with regularization) """
# number of stimulation lines/patterns
eit = jac.JAC(mesh_obj, el_pos, ex_mat, step, perm=1.0, parser="fmmu")
eit.setup(p=0.25, lamb=1.0, method="lm")
# lamb = lamb * lamb_decay
ds = eit.gn(fv, lamb_decay=0.1, lamb_min=1e-5, maxiter=20, verbose=True)

# plot
fig, ax = plt.subplots(figsize=(6, 4))
im = ax.tripcolor(
    pts[:, 0],
    pts[:, 1],
    tri,
    np.real(ds),
    shading="flat",
    alpha=1.0,
    cmap=plt.cm.viridis,
)
fig.colorbar(im)
ax.axis("equal")
ax.set_title("Conductivities Reconstructed")
# fig.savefig('../figs/demo_static.png', dpi=96)
plt.show()
```

_Originally posted by @liubenyuan in https://github.com/liubenyuan/pyEIT/issues/15#issuecomment-741722298_

**Comment by SetsunaRiku** [comment]
Thank you!
The simulation runs very well with `rotate_meas` protocol until I change the `_natural_boundary` to 0.01 and -0.01 (I used 10 mA constant current in my experiments.). Is the reconstructed conductivity dimensionless? or can the difference of `ds` obtained from two tests be used as the conductivity change?

**Comment by liubenyuan** [comment]
Hi, you can safetly pass `_natural_boundary` to 1 and -1. This is a unit current simplification. You may than scale the reconstructed results given the dimensions of your meshes.

If you want to image to differences, you can use difference/dynamic EIT, which is more robust than reconstruct the static image at two timestamps and then subtract them.
