### ISSUE TITLE
BP(back projection) does not work properly for opposite stimulation protocol.

### ISSUE THREAD

**Issue by ultrach** [liubenyuan/pyEIT#19]
Hi. 

I tested the example "eit_dynamic_bp.py". 
It runs well at the default setting, 
but if I change the scanning conditions, 

el_dist, step = 1, 1 ==> el_dist, step = 8, 1

the result is weird like as below.
![Figure_1](https://user-images.githubusercontent.com/46465238/105936328-d16eea00-6096-11eb-8e2b-97d07ccdc60c.png)

Does the BP solver not support the opposite stimulation protocol? 
or Is there anything i am missing? 

Thank you in advance.

**Comment by liubenyuan** [comment]
Hi, Its a bug in BP normalization. I have updated the BP solver as well as the BP example.

Sorry for the inconvenience and the late reply.

**Comment by ultrach** [comment]
Hi. Thank you for your kind support. pyEIT is a great help to me.

**Comment by liubenyuan** [comment]
@ultrach It would be great if you cited our article in your research, haha.

**Comment by ultrach** [comment]
If I have an oppotunity, I'll gradly do that. 
By the way, the opposite protocol(el_dist=8, n_el=16) for bp solver result is still weired. TT

**Comment by liubenyuan** [comment]
Yeah, you can not assign `n_el=16` if the total number of electrode is 16, in this way, the two nodes of voltage meter is `a=i`, `b=(i+16)%16=i`, which is the same electrode.
