### ISSUE TITLE
Question regarding Jacobians

### ISSUE THREAD

**Issue by akarshp28** [liubenyuan/pyEIT#25]
Hello @liubenyuan,

I hope you are doing well. First of all, thank you so much for developing and sharing your pyEIT library with everyone. I am fairly new to using your library so, I have some questions for you with regards to the Forward class provided below.
https://github.com/liubenyuan/pyEIT/blob/eaa0b7981b6ab0735e25ba079c1ecc209604c438/pyeit/eit/fem.py#L17

If I understand correctly, you provide the Jacobian of the body with respect to the electric potential "u" and conductivity "sigma" using solve and solve_eit functions respectively from the above Forward class.
So, "solve" computes the forward problem by outputting the point wise potential u values and Jacobian of u.
While, "solve_eit" computes the inverse problem by outputting the Jacobian of sigma, boundary voltages at electrodes and Smear matrix.
Please correct my understanding if I am wrong here.

I am particularly interested in the Jacobian information from your library. My main questions are:
1. These Jacobians are w.r.t the simplex triangles i.e, df(body, sigma)/d sigma and df(body, u)/d u at each triangle on the mesh correct?
2. Do you know if there is a way I can compute the individual gradients du/dx, du/dy, d sigma/dx and d sigma/dy for each x, y on the mesh?

Any advice is greatly appreciated,

Thank you so much,

**Comment by liubenyuan** [comment]
Hi, Yes you are right.

1, The detailed Jacobian calculation code is based on "Direct EIT Jacobian calculations for conductivity change and electrode movement", which can be download at https://iopscience.iop.org/article/10.1088/0967-3334/29/6/S08/pdf

2, You mean position jacobian? If so, you may refer this article, "Methods for calculating the electrode position Jacobian for impedance imaging", https://iopscience.iop.org/article/10.1088/1361-6579/aa5b78

**Comment by akarshp28** [comment]
Thank you for the reference papers @liubenyuan. I will go through the 1st paper to get better understanding.

No, I am not referring to position Jacobian. I think position Jacobian refers to the values of derivatives when there is movement in electrodes as per the 2nd ref paper, if I am not wrong.

What I want is very simple. From the theoretical standpoint as you already know, the standard PDE's for EIT are given by the following:
![](https://i.ibb.co/wBrWccp/Code-Cogs-Eqn-8.png)
f is input current, g is measured boundary voltage.

If I simply expand the 1st and 2nd PDEs from above equ, I get the following:
Main pde in domain:
![](https://i.ibb.co/xJ7qTGP/Code-Cogs-Eqn.png)

Neumann condition on boundary (i am assuming the default circle mesh):
![](https://i.ibb.co/tCJJ3Jf/Code-Cogs-Eqn-1.png)

Now for fixed electrodes without any movement nor any other randomness like the 2nd reference paper, I simply want to know if I can calculate these du/dx, du/dy, d sigma/dx and d sigma/dy values via simulations for each x, y point inside the domain and on the boundary for any given tissue inside our circle mesh.

Hope the explanation for my question is clear. Thank you so much for your time @liubenyuan.
