### ISSUE TITLE
Problem with  solve and normalize with base.py for back projection reconstruction

### ISSUE THREAD

**Issue by ccfbeltran** [liubenyuan/pyEIT#26]
I tried to use dynamic imaging (conductivities imaging) for back projection
ds = 192 * eit.solve(v1, v0,normalize=true)

with v1 being a 780x280 matrix and v0 a 280 row vector.

But I have a problem with the dot operation (1002x208 cant dot with 780x208 matrix) Its a common mathematical issue. Is it possible to explain a little why this error is happening? I tried to transpose the 780x208 matrix for the dot operation but I receive a 1002x780 matrix as a response for the eit.solve operation and Im not sure how to reconstruct that response on an image. 
Is there something that I'm not following correctly? 

thanks for your help!

**Comment by liubenyuan** [comment]
Do you mean that `v1` is a multiple measurement vector (MMV) with 780 frames and each frame is a EIT measurement whose size is 208? When `V1` is the MMV model, BP or dynamic imaging tries to reconstruct the image of each frame, i.e., V1[i] - V0, and the result matrix, `ds`, is EIT image sequences of Mx780, where M is the size of the ith image and 780 is the frame number.

**Comment by ccfbeltran** [comment]
perfect thx!
