### ISSUE TITLE
Input of real world data

### ISSUE THREAD

**Issue by PclFnr** [liubenyuan/pyEIT#31]
Hi @liubenyuan,

thanks for this great project.

I was wondering how you could work with voltage measurements taken from the real world. If you imagine that you take a voltage measurement and get a pandas time series (like with the load_csv(fstr, resample=None) method from pyeit/io/icp.py), how would you proceed in the code to generate an EIT image?

Thank you and kind regards,
Pascal

**Comment by liubenyuan** [comment]
We have used real-world data (head and lung) in **dynamic** imaging.
You may firstly check the examples folder and the [eitmesh](https://github.com/liubenyuan/eitmesh) project which provides the meshes we used in head and lung imaging. As well as the [pyeit-apps](https://github.com/liubenyuan/pyeit-apps) projects which host some experimental data from daeger.

We will release our data this year.
