### ISSUE TITLE
Reconstruction different from older versions

### ISSUE THREAD

**Issue by ChabaneAmaury** [liubenyuan/pyEIT#33]
I was working with a previous version of this package, and I built myself a dataset as well, and for some reasons the new version is now unable to reconstruct properly from my saved data. The reconstruction was changed in the last 3 months maximum, and the version I was working with was still not available on pypi. 

Any idea on how to fix this without reconstructing my entire dataset?

**Comment by liubenyuan** [comment]
could you tell me the HEAD of your last usable version?

**Comment by ChabaneAmaury** [comment]
Unfortunately not...I tried rolling back to an older version manually by referring to an old commit reference (6+ months ago), but it seems to have the same issue. My guess is that the algorithm for either measurements' generation or gauss-newtonian is slightly different from one computer to another (I was on a different computer), and that it changed completely the results. I am currently regenerating my entire dataset since I don't have time to look into a workaround. If you need any more information, feel free to refer to me, but I am no longer going to check up on that. Thank you anyway for your time!

**Comment by liubenyuan** [comment]
Could you find the git tip of your last working repository? Is it relate to the forward solver? I can build a change log for you if this could help.

**Comment by ChabaneAmaury** [comment]
It seems to be related to the forward solver and the mesh apparently, at least that's what I got from my tests, but I started to recreate the dataset anyway...
This commit should be the last one working in my case : eaa0b7981b6ab0735e25ba079c1ecc209604c438

**Comment by liubenyuan** [comment]
Hi, I've checked the code. Are you using `normalize=True` in your reconstruction code? you can revert to cb3cfa603

The problem might be related the normalization code, https://github.com/liubenyuan/pyEIT/blob/cb3fcfa603c2a34c9739487200209b70a782fd3e/pyeit/eit/base.py#L122

Since 4d4b081, this normalization changed to `(v1 - v0) / v0 * v0_sign`, which might be inaccurate if you are using complex-valued imaging. You can revert to `(v1 - v0) / np.abs(v0)` to this commit or change this line in `base.py`

**Comment by liubenyuan** [comment]
Could you please try the latest commit 3487ece ?

**Comment by ChabaneAmaury** [comment]
I am not using `normalize=True`, so I don't know if it is related or not. I will try the new update in some days, when I will be done with the dataset. I'll let you know once this is done!
