### ISSUE TITLE
pyeit-1.1.9: Generate realistic head and lung meshes!

### ISSUE THREAD

**Issue by DavidMetzIMT** [liubenyuan/pyEIT#41]
### Discussed in https://github.com/liubenyuan/pyEIT/discussions/39

<div type='discussions-op-text'>

<sup>Originally posted by **liubenyuan** April 15, 2022</sup>
## What's Changed
* Improved f solver calculation by @ChabaneAmaury in https://github.com/liubenyuan/pyEIT/pull/37
* Optimize .et3 and .mes loading routine. Generate optimized thorax shape using distmesh and shapely by @liubenyuan in https://github.com/liubenyuan/pyEIT/pull/38
* Generate High quality Head (symmetric) and Lung meshes.

**Full Changelog**: https://github.com/liubenyuan/pyEIT/compare/v1.1.8...v1.1.9

<hr /><em>This discussion was created from the release <a href='https://github.com/liubenyuan/pyEIT/releases/tag/v1.1.9'>pyeit-1.1.9: Generate realistic head and lung meshes!</a>.</em></div>

**Comment by DavidMetzIMT** [comment]
Hy @liubenyuan,

I have tried the v1.1.9 with the improved f solver calculation but only with standard computation and I'm getting a singular matrix error, see below.
```
File "C:\Anaconda_src\pyeit\pyeit\eit\jac.py", line 34, in setup
    self.H = h_matrix(self.J, p, lamb, method)
  File "C:\Anaconda_src\pyeit\pyeit\eit\jac.py", line 217, in h_matrix
    h_mat = np.dot(la.inv(j_w_j + lamb * r_mat), jac.transpose())
  File "C:\Anaconda3\envs\ai-app\lib\site-packages\scipy\linalg\_basic.py", line 968, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.LinAlgError: singular matrix
```

I printed out self.J before computing self.H to control it:

```
print(f'{self.J=}')
self.H = h_matrix(self.J, p, lamb, method)

>> self.J=array([], shape=(0, 4422), dtype=float64)
```

I tested also older code. Until the commit (e6894cab1a3c566503dda5529546c53639f71e51 ("using black 22.3")) , the one right before the "Import vectorized code from ChabaneAmaury (#36)" I don't get that error! ... self.J is not empty...

self.J=array([[-2.36116938e-05, -7.21964958e-07, -8.22255804e-07, ...,
        -3.73798629e-06, -3.33546922e-06, -3.19049582e-06],
       [-1.35992657e-05, -7.36976401e-07, -7.56589122e-07, ...,
        -2.94812718e-06, -2.66728410e-06, -2.54024640e-06],
       [-9.00432002e-06, -8.14572820e-07, -7.53190796e-07, ...,
        -2.52075287e-06, -2.31271585e-06, -2.19552974e-06],
       ...,
       [ 2.37314576e-04, -1.18682493e-06, -2.29461818e-06, ...,
        -1.79361171e-05, -1.71229763e-05, -1.61382364e-05],
       [-1.12155333e-04, -9.35177002e-07, -1.51968162e-06, ...,
        -1.15728896e-05, -1.01823273e-05, -9.72948691e-06],
       [-1.06183491e-04, -8.11221827e-07, -1.15533129e-06, ...,
        -7.36480352e-06, -6.44492061e-06, -6.18616215e-06]])




I don't understand what is happening here, because after reviewing the code : @ChabaneAmaury made everything right to assure good back compatility. 
@liubenyuan and @ChabaneAmaury:  you  have maybe an idea where is comming from ? or I just missing to something new to set!

**Comment by ChabaneAmaury** [comment]
> 

I personally don't have any issues when trying to replicate your issue. Have you tried with a fresh environment?

**Comment by liubenyuan** [comment]
I could not reproduce this error. Could you provide a minimal example or running a specific example file?

I think we should add a unit test suite for validate these functions.

**Comment by DavidMetzIMT** [comment]
Hy guys,

I found a minimal error in voltage_meter see https://github.com/liubenyuan/pyEIT/pull/42

**Comment by liubenyuan** [comment]
I think this issue can be closed. Thank you.
