### ISSUE TITLE
more flexible electrode configurations? 

### ISSUE THREAD

**Issue by JeanRintoul** [liubenyuan/pyEIT#5]
I would like to model a larger array of varied electrode configurations, from the standard tetrapolar adjacent method, opposition method, to bipolar and other user defined electrode configurations that don't always have the same step size. Currently functions seem limited to tetrapolar adjacent/opposition only. Is there a way to allow a user defined file(example)
[e_config.txt](https://github.com/liubenyuan/pyEIT/files/1858113/e_config.txt)

Above is an example of a 32 electrode configuration running in random order. Ideally it should acquire the same results as running the simulator but it doesn't as there are dependencies in other files on electrode ordering.

**Comment by liubenyuan** [comment]
`pyEIT` does not constrain the stimulation pattern, for example, you can use the variable `ex_mat` for more flexible configurations of the stimulation electrodes. `ex_mat` is of size `Nx2`, for any row `ex_mat_i`, the `ex_mat_i(0)` is the current injection while `ex_mat_i(1)` is the sink.

For a typical 16-electrodes configuration, the electrodes are at nodes:
```
[1, 7, 86, 176, 288, 667, ..., 981]
```
and `ex_mat` may be specified within the range `[1..16]`
```
1, 3
1, 7
2, 9,
1, 16,
2, 15
...
7, 1
8, 2
```

You may find an example in `demo_stack_jac.py` and `demo_sensitivity2d.py`

But, as you see in the function `voltage_meter`, the measuring pattern is limited to `adjacent`. However, the measuring sequence only affects the dynamic range in real hardware, in simulation, adjacent measurement method suffices.

**Comment by JeanRintoul** [comment]
Thanks - I am taking a look at those demos. I have an 8 electrode hardware system which I plan to integrate with pyEIT that is bipolar only- is that a possible configuration currently allowed, can you set skip k to 0 to designate bipolar?
I have another 32 differential referencing system currently getting fabricated which I'd like to use your reconstruction library for to integrate into OpenEIT real-time dashboard. 
One set of tests I'd like to try with the goal of improving dynamic range, is reconstruction with different step sizes in the same 32 electrode tetrapolar reconstruction. Idea is that this may slightly improve spatial resolution. So the question is can skip k be 0 for bipolar, and can you have different values for k in the same reconstruction(i.e. 2 and 3 and 4 and 5 etc all in one reconstruction)?

**Comment by JeanRintoul** [comment]
Great - demo_dynamic_stack can vary A and B but is there a way to vary M and N as well?  
Also, is there a way to do bipolar measurements where M and N are non-existent? Intent is to use in hardware and experiment with different configurations here.

**Comment by liubenyuan** [comment]
The current code only varies A and B. M and N are fixed by a skip k pattern (step=k). However, given that,
`\int u_i = 0, i \in E_l`, by measuring all adjacent voltage differences on the boundary electrodes, you may infer the voltage difference of any pair (exclude the A and B which have contact impedance). The way the voltage meter constructs only affect the dynamic ranges and noise performance in **real** hardware, in simulation, the DR and SNR (of ADC) are assumed infinity.

However, pyEIT cannot handle the voltage meter while M and N are not electrodes. **In this case, you may create pseudo electrodes.** For example, 71 electrodes marked by `el_pos`, but keep in might which of these electrodes are those actual 16 electrodes you want to use, and write `ex_mat` (A and B) accordingly. M and N are also measured in an adjacent manner, then you may infer any voltage difference of these 71 measures.

**Comment by JeanRintoul** [comment]
Thanks for clarifying SNR assumed infinity in simulation. Currently integrating pyEIT into OpenEIT dashboard.

**Comment by liubenyuan** [comment]
Now electrode configurations has been merged into Protocol dataset as in #47. User could specify `meas_pattern` or build it if necessary.

**Comment by veelox321** [comment]
Hi, is there a reason i just cant seem to reconstruct using a different patern than adjacent? The ex_mat and meas_mat seems ok if i do skip2 but any reconstruction doesn't work even by adjusting the constant : w,lamb,n,....

**Comment by JeanRintoul** [comment]
Hello, If you want to try any sequence you specify you should also update the firmware to match. The firmware is also open source.

**Comment by veelox321** [comment]
> Hello, If you want to try any sequence you specify you should also update the firmware to match. The firmware is also open source.

Hi, thanks for your quick reply. I already have an updated firmware which match the excitation pattern im trying to reconstruct. Data are acquired on circular phantom
