### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by xlzhang517** [liubenyuan/pyEIT#56]
Hi, 
totay, i install pyeit by "conda install -c conda-forge pyeit", 
but when i run "python eit_dynamic_bp.py" for test,  i have some problem as follow, 
i dont know why where is wrong, hope your answer.
Traceback (most recent call last):
  File "E:\pyEIT\examples\fem_forward2d.py", line 38, in <module>
    protocol_obj = protocol.create(n_el, dist_exc=7, step_meas=1, parser_meas="std")
  File "E:\pyEIT2\lib\site-packages\pyeit\eit\protocol.py", line 188, in create
    return PyEITProtocol(ex_mat, meas_mat)
TypeError: __init__() takes 1 positional argument but 3 were given

BR,
xlzhang.

**Comment by liubenyuan** [comment]
I test it under windows 11, python 3.10.4, and run both `eit_dynamic_bp.py` and `fem_forward2d.py`, and it reports no error. Could you please share the PYTHONPATH settings and python, numpy versions?

**Comment by xlzhang517** [comment]
> Just now, i replace the whole file "protocol.py" contents using "protocol.py" of the source code, and it works. 
THANKS VERY MUCH!

**Comment by liubenyuan** [comment]
Haha, so could you do a diff and upload the differences?

**Comment by xlzhang517** [comment]
The difference between two file is the position of  "ex_mat: np.ndarray meas_mat: np.ndarray" in class PyEITProtocol .
Version has problem: 
    """
    EIT Protocol buid-in protocol object
    ex_mat: np.ndarray
    meas_mat: np.ndarray
    """
however, right version is 
    """
    EIT Protocol buid-in protocol object
    """
    ex_mat: np.ndarray
    meas_mat: np.ndarray

**Comment by liubenyuan** [comment]
I checked recent version of pyeit on `conda-forge`, [pyeit](https://anaconda.org/conda-forge/pyeit/files?page=2), they are ok with the right `PyEITProtocol` parameters. So this might be that some codes have been accidentally commented out.
