### ISSUE TITLE
Negative voltage for fwd.solve_eit

### ISSUE THREAD

**Issue by ccfbeltran** [liubenyuan/pyEIT#64]
Hi I have a question. 
when doing this function when transforming from mesh to voltage
`f1 = fwd.solve_eit(ex_mat, step=step, perm=mesh_obj["perm"])`
I received some negative voltage on the 208 array(f1.v). 

I don't understand why I am receiving negative data. Using conventional data acquisition on a human, I don't receive any negative voltage. So I'm trying to have the same results from the algorithm.

Thanks for the help :)

**Comment by liubenyuan** [comment]
The boundary measurement are complex-valued voltage differences on adjacent electrodes, So there might  be negative measurements if you are using opposition excitation configurations.
In real life applications, adjacent stimulation is often used. And the boundary measurements are taking a abs value for the physical meaning of impedance.

**Comment by ccfbeltran** [comment]
when you are saying opposition excitation configurations, are you talking about this kind of measurement?
![opposite excitation adjacent](https://user-images.githubusercontent.com/46805838/185811681-34351424-c503-4306-806b-0818a91669d8.jpg)

if so, what I'm looking for is to do adjacent excitation so this way: 
![image](https://user-images.githubusercontent.com/46805838/185811706-c9142593-5564-413e-8054-f892dca4a37b.png)

is there a way to simulate that for the  fwd.solve_eit?

thanks for your help is really appreciated!

**Comment by liubenyuan** [comment]
sure, newer version of pyeit use a PyEIT.Protocol dataclass to specify the stimulation pattern. You can use `protocol_obj = protocol.create(16, dist_exc=1, step_meas=1, parser_meas="fmmu")` for the below illustration figure.

**Comment by ccfbeltran** [comment]
thanks!
