### ISSUE TITLE
Injected current

### ISSUE THREAD

**Issue by Zhangbowen111** [liubenyuan/pyEIT#9]
Thank you for your program, it helped me a lot. Can I ask you a question? where is the progamm, defines the input current amplitude, or the injecting current is considered/set as 1A or 1mA, automatically.

**Comment by liubenyuan** [comment]
It is assumed 1 unit by default.

It can be amplified, by modifying the coeds in fem.py

**Comment by Zhangbowen111** [comment]
thank you for your reply

> It is assumed 1 unit by default.
> 
> It can be amplified, by modifying the coeds in fem.py

**Comment by Zhangbowen111** [comment]
Sorry to bother you again
In the wrapper.py file, in line 71 as "# 4. init uniform element permittivity (sigma)". Em, I understand the "permittivity" as "epsilon" instead of "sigma". 
So, I understand this "perm" array as the conductivity distribution within the object (as: sigma + jw*epsilon). Am I right? :D

**Comment by liubenyuan** [comment]
Yes, you are right. It can be complex valued
